version: '2'
services:
    web:
        build: ./upload_proj
        command: python manage.py runserver 127.0.0.1:8000
        command: python manage.py makemigrations
        command: python manage.py migrate
        volumes:
            - .:/code
        ports:
            - "8000:8000"
