# Generated by Django 3.1.3 on 2020-11-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(choices=[('IPAD', 'ipad'), ('PLAYSTATION', 'playstation'), ('TV', 'tv')], max_length=11),
        ),
    ]
