# Generated by Django 3.1.3 on 2020-11-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20201111_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(choices=[('PLAYSTATION', 'playstation'), ('IPAD', 'ipad'), ('TV', 'tv')], max_length=11),
        ),
    ]
