# Generated by Django 3.1.3 on 2020-11-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20201112_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(choices=[('PLAYSTATION', 'playstation'), ('TV', 'tv'), ('IPAD', 'ipad')], max_length=11),
        ),
    ]
