# Generated by Django 3.1.3 on 2020-11-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20201112_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=20)),
                ('item', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=1, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(choices=[('TV', 'tv'), ('PLAYSTATION', 'playstation'), ('IPAD', 'ipad')], max_length=11),
        ),
    ]
