# Generated by Django 3.1.3 on 2020-11-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20201113_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(choices=[('IPAD', 'ipad'), ('TV', 'tv'), ('PLAYSTATION', 'playstation')], max_length=11),
        ),
    ]
