# Generated by Django 3.1.3 on 2020-11-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20201113_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(choices=[('PLAYSTATION', 'playstation'), ('TV', 'tv'), ('IPAD', 'ipad')], max_length=11),
        ),
    ]
