# Generated by Django 3.1.3 on 2020-11-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20201113_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Richuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('spent_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gems', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='deal',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(choices=[('TV', 'tv'), ('IPAD', 'ipad'), ('PLAYSTATION', 'playstation')], max_length=11),
        ),
    ]
