# Generated by Django 3.1.3 on 2020-11-15 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20201115_1048'),
        ('csvs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichuserView',
            fields=[
                ('richuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.richuser')),
            ],
            bases=('sales.richuser',),
        ),
    ]
